/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
    { code: "en", name: "English", nativeName: "English" },
    { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
    { code: "bn", name: "Bengali", nativeName: "বাংলা" },
    { code: "te", name: "Telugu", nativeName: "తెలుగు" },
    { code: "mr", name: "Marathi", nativeName: "मराठी" },
    { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
    { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
    { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
    { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
    { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
    { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
    { code: "as", name: "Assamese", nativeName: "অসমীয়া" },
    { code: "mai", name: "Maithili", nativeName: "মৈথিলী" },
    { code: "sat", name: "Santali", nativeName: "ᱥᱟᱱᱛᱟᱲᱤ" },
    { code: "ks", name: "Kashmiri", nativeName: "कश्मीरी / كشميري" },
    { code: "ne", name: "Nepali", nativeName: "नेपाली" },
    { code: "sd", name: "Sindhi", nativeName: "सिंधी / سنڌي" },
    { code: "kok", name: "Konkani", nativeName: "कोंकणी" },
    { code: "doi", name: "Dogri", nativeName: "डोगरी" },
    { code: "mni", name: "Manipuri", nativeName: "মৈতৈলোন" },
    { code: "brx", name: "Bodo", nativeName: "बड़ो" },
    { code: "sa", name: "Sanskrit", nativeName: "संस्कृतम्" },
    { code: "ur", name: "Urdu", nativeName: "اردو" }
];

const translations = {
    en: {
        brandName: "Kisan Sahayak",
        navFeatures: "Features",
        navAbout: "About",
        navLogin: "Login",
        navSignUp: "Sign Up",
        navShop: "Shop",
        welcomeUser: "Welcome, {name}",
        logout: "Logout",
        selectLanguage: "Select Language",
        footerMadeWith: "Made with ❤️ for Indian Farmers.",
        footerEmpowering: "Empowering Farmers.",
        aboutUs: "About Us",
        welcomeBack: "Welcome Back",
        signInAccount: "Sign in to your account",
        emailPlaceholder: "Email",
        passwordPlaceholder: "Password",
        signInBtn: "Sign In",
        noAccount: "Don't have an account?",
        signUp: "Sign up",
        joinAdvisory: "Join Crop Advisory",
        createAccount: "Create your account",
        namePlaceholder: "Full Name",
        pincodePlaceholder: "Pincode (for location)",
        hasAccount: "Already have an account?",
        signInLink: "Sign in",
        heroBadge: "Trusted by 10,000+ Farmers",
        heroTitle1: "Empowering ",
        heroTitle2: "Farmers",
        heroTitle3: " with Smart Advice",
        heroDesc: "Kisan Sahayak uses advanced AI to provide real-time agricultural insights, weather alerts, and market prices to help you farm smarter and earn more.",
        ctaGetStarted: "Get Started for Free",
        ctaViewDemo: "View Demo",
        featuresTitle: "Everything you need to succeed",
        featuresDesc: "We combine cutting-edge technology with traditional farming wisdom to provide the best possible support for your fields.",
        f1Title: "AI Crop Recommendation",
        f1Desc: "Get personalized crop suggestions based on your soil and local climate conditions.",
        f2Title: "Weather Insights",
        f2Desc: "Real-time weather updates and alerts to help you plan your farming activities better.",
        f3Title: "Mandi Prices",
        f3Desc: "Stay updated with the latest market rates from nearby mandis to get the best price for your produce.",
        f4Title: "AI Chatbot Support",
        f4Desc: "Instant answers to your farming queries from our intelligent AI assistant.",
        readyTitle: "Ready to grow your harvest?",
        readyDesc: "Join thousands of farmers who are already using Kisan Sahayak to make better decisions every day.",
        readyBtn: "Create Account Now",
        advTitle: "Crop Advisor",
        lblSeason: "Season",
        lblSoil: "Soil Type",
        lblWater: "Water Availability",
        lblLand: "Land Area (Acres)",
        optRabi: "Rabi (Winter)",
        optKharif: "Kharif (Monsoon)",
        optZaid: "Zaid (Summer)",
        optLoamy: "Loamy",
        optClay: "Clay",
        optSandy: "Sandy",
        optBlack: "Black Soil",
        optLow: "Low",
        optMedium: "Medium",
        optHigh: "High",
        btnAnalyzing: "Analyzing Soil...",
        btnGetRec: "Get Recommendations",
        bestMatch: "Best Match",
        goodMatch: "Good Match",
        expYield: "Exp. Yield",
        qPerAcre: "q/acre",
        estRevenue: "Est. Revenue",
        basedOnMarket: "Based on current market price",
        marketUnavailable: "Live market price unavailable",
        demand: "Demand",
        risk: "Risk",
        companionCrops: "Companion Crops (Intercropping)",
        fertSchedule: "Fertilizer Schedule",
        expertTip: "Expert Farmer Tip",
        hideDetails: "Hide Details",
        viewFullGuide: "View Full Guide",
        priceTitle: "Mandi Prices",
        pricePlaceholder: "Enter crop (e.g. Wheat, Rice)",
        btnChecking: "Checking...",
        cached: "Cached",
        estimated: "Estimated",
        perQuintal: "per quintal",
        updated: "Updated:",
        weatherUnavailable: "Weather Unavailable",
        humidity: "Humidity:",
        wind: "Wind:",
        aboutHeroTitle1: "About ",
        aboutHeroTitle2: "Kisan Sahayak",
        aboutHeroDesc: "We are a passionate team dedicated to empowering India's farmers with technology. Our mission is to provide accurate, timely, and actionable advice to maximize crop yields.",
        meetTeam: "Meet the Team",
        getInTouch: "Get in Touch",
        getInTouchDesc: "Have questions, suggestions, or just want to say hi? We'd love to hear from you. Drop us an email!",
        sendEmailBtn: "Send us an Email",
        botGreeting: "Namaste! I am Kisan Sahayak AI. Ask me anything about your crops.",
        botPlaceholder: "Ask about fertilizer, pests...",
        shopTitle: "Farmer's Marketplace",
        shopDesc: "High quality seeds, fertilizers, pumps, and agricultural equipment at affordable prices.",
        addToCart: "Add to Cart",
        cartTitle: "Your Cart",
        checkout: "Buy Now",
        filterAll: "All Supplies",
        filterSeeds: "Seeds",
        filterFertilizers: "Fertilizers",
        filterEquipment: "Equipment",
        filterPumps: "Pumps & Irrigation",
        filterPesticides: "Pesticides",
        filterTools: "Tools",
        priceRs: "₹{price}"
    },
    hi: {
        brandName: "किसान सहायक",
        navFeatures: "विशेषताएं",
        navAbout: "हमारे बारे में",
        navLogin: "लॉगिन",
        navSignUp: "रजिस्टर करें",
        navShop: "दुकान (Shop)",
        welcomeUser: "स्वागत है, {name}",
        logout: "लॉग आउट",
        selectLanguage: "भाषा चुनें",
        footerMadeWith: "भारतीय किसानों के लिए ❤️ से निर्मित।",
        footerEmpowering: "किसानों को सशक्त बनाना।",
        aboutUs: "हमारे बारे में",
        welcomeBack: "वापसी पर स्वागत है",
        signInAccount: "अपने खाते में लॉगिन करें",
        emailPlaceholder: "ईमेल",
        passwordPlaceholder: "पासवर्ड",
        signInBtn: "लॉगिन करें",
        noAccount: "खाता नहीं है?",
        signUp: "साइन अप करें",
        joinAdvisory: "फसल सलाह से जुड़ें",
        createAccount: "अपना नया खाता बनाएं",
        namePlaceholder: "पूरा नाम",
        pincodePlaceholder: "पिनकोड (स्थान के लिए)",
        hasAccount: "पहले से खाता है?",
        signInLink: "लॉगिन करें",
        heroBadge: "10,000+ किसानों द्वारा भरोसेमंद",
        heroTitle1: "सटीक सलाह से ",
        heroTitle2: "किसानों",
        heroTitle3: " को बनाएं सशक्त",
        heroDesc: "किसान सहायक आपको रीयल-टाइम मौसम अलर्ट, मंडी भाव और वैज्ञानिक फसल सलाह देने के लिए एआई का उपयोग करता है।",
        ctaGetStarted: "मुफ्त में शुरू करें",
        ctaViewDemo: "डेमो देखें",
        featuresTitle: "सफलता के लिए आवश्यक सब कुछ",
        featuresDesc: "हम आपके खेतों के लिए सर्वोत्तम सहायता प्रदान करने के लिए पारंपरिक कृषि ज्ञान के साथ आधुनिक तकनीक को जोड़ते हैं।",
        f1Title: "AI फसल अनुशंसा",
        f1Desc: "अपनी मिट्टी और स्थानीय जलवायु परिस्थितियों के आधार पर व्यक्तिगत फसल सुझाव प्राप्त करें।",
        f2Title: "मौसम की जानकारी",
        f2Desc: "आपकी कृषि गतिविधियों की बेहतर योजना बनाने के लिए रीयल-टाइम मौसम अपडेट और अलर्ट।",
        f3Title: "मंडी के भाव",
        f3Desc: "अपनी उपज की सर्वोत्तम कीमत पाने के लिए नजदीकी मंडियों की नवीनतम बाजार दरों से अपडेट रहें।",
        f4Title: "AI चैटबॉट सहायता",
        f4Desc: "हमारे बुद्धिमान एआई सहायक से अपने कृषि प्रश्नों के त्वरित उत्तर पाएं।",
        readyTitle: "क्या आप अपनी फसल बढ़ाने के लिए तैयार हैं?",
        readyDesc: "उन हजारों किसानों से जुड़ें जो हर दिन बेहतर निर्णय लेने के लिए किसान सहायक का उपयोग कर रहे हैं।",
        readyBtn: "अभी खाता बनाएं",
        advTitle: "फसल सलाहकार",
        lblSeason: "मौसम (Season)",
        lblSoil: "मिट्टी का प्रकार",
        lblWater: "पानी की उपलब्धता",
        lblLand: "भूमि क्षेत्रफल (एकड़)",
        optRabi: "रबी (सर्दियां)",
        optKharif: "खरीफ (मानसून)",
        optZaid: "जायद (गर्मियां)",
        optLoamy: "दोमट मिट्टी",
        optClay: "चिकनी मिट्टी",
        optSandy: "रेतीली मिट्टी",
        optBlack: "काली मिट्टी",
        optLow: "कम",
        optMedium: "मध्यम",
        optHigh: "अधिक",
        btnAnalyzing: "मिट्टी का विश्लेषण जारी...",
        btnGetRec: "सुझाव प्राप्त करें",
        bestMatch: "सर्वोत्तम फसल",
        goodMatch: "उपयुक्त फसल",
        expYield: "अनुमानित उपज",
        qPerAcre: "क्विंटल/एकड़",
        estRevenue: "अनुमानित आय",
        basedOnMarket: "वर्तमान बाजार मूल्य के आधार पर",
        marketUnavailable: "लाइव बाजार मूल्य उपलब्ध नहीं",
        demand: "बाजार मांग",
        risk: "जोखिम",
        companionCrops: "सह-फसल (Intercropping)",
        fertSchedule: "उर्वरक (खाद) शेड्यूल",
        expertTip: "विशेषज्ञ किसान टिप",
        hideDetails: "विवरण छुपाएं",
        viewFullGuide: "पूरी गाइड देखें",
        priceTitle: "मंडी भाव",
        pricePlaceholder: "फसल का नाम लिखें (जैसे गेहूं, धान)",
        btnChecking: "जांच जारी...",
        cached: "सहेजा गया",
        estimated: "अनुमानित",
        perQuintal: "प्रति क्विंटल",
        updated: "अपडेट किया गया:",
        weatherUnavailable: "मौसम डेटा अनुपलब्ध",
        humidity: "आर्द्रता (Humidity):",
        wind: "हवा:",
        aboutHeroTitle1: "हमारे ",
        aboutHeroTitle2: "बारे में",
        aboutHeroDesc: "हम एक जुनूनी टीम हैं जो भारत के किसानों को तकनीक से सशक्त बनाने के लिए समर्पित हैं।",
        meetTeam: "हमारी टीम से मिलें",
        getInTouch: "संपर्क करें",
        getInTouchDesc: "कोई प्रश्न या सुझाव है? हम आपसे सुनना पसंद करेंगे। हमें ईमेल भेजें!",
        sendEmailBtn: "हमें ईमेल भेजें",
        botGreeting: "नमस्ते! मैं किसान सहायक AI हूँ। अपनी फसलों या खेती के बारे में कुछ भी पूछें।",
        botPlaceholder: "खाद, कीटनाशक, मौसम के बारे में पूछें...",
        shopTitle: "किसान बाज़ार (Shop)",
        shopDesc: "उच्च गुणवत्ता वाले बीज, खाद, पंप और कृषि उपकरण किफायती दामों पर।",
        addToCart: "कार्ट में जोड़ें",
        cartTitle: "आपकी कार्ट",
        checkout: "अभी खरीदें",
        filterAll: "सभी सामग्री",
        filterSeeds: "बीज (Seeds)",
        filterFertilizers: "उर्वरक एवं खाद",
        filterEquipment: "कृषि उपकरण",
        filterPumps: "पंप और सिंचाई",
        filterPesticides: "कीटनाशक",
        filterTools: "औजार",
        priceRs: "₹{price}"
    },
    pa: {
        brandName: "ਕਿਸਾਨ ਸਹਾਇਕ",
        navFeatures: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
        navAbout: "ਸਾਡੇ ਬਾਰੇ",
        navLogin: "ਲਾਗਇਨ",
        navSignUp: "ਰਜਿਸਟਰ",
        navShop: "ਦੁਕਾਨ",
        welcomeUser: "ਜੀ ਆਇਆਂ ਨੂੰ, {name}",
        logout: "ਲਾਗ ਆਊਟ",
        selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
        footerMadeWith: "ਭਾਰਤੀ ਕਿਸਾਨਾਂ ਲਈ ❤️ ਨਾਲ ਬਣਾਇਆ ਗਿਆ।",
        footerEmpowering: "ਕਿਸਾਨਾਂ ਨੂੰ ਸਸ਼ਕਤ ਬਣਾਉਣਾ।",
        aboutUs: "ਸਾਡੇ ਬਾਰੇ",
        welcomeBack: "ਵਾਪਸੀ 'ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ",
        signInAccount: "ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਲਾਗਇਨ ਕਰੋ",
        emailPlaceholder: "ਈਮੇਲ",
        passwordPlaceholder: "ਪਾਸਵਰਡ",
        signInBtn: "ਲਾਗਇਨ ਕਰੋ",
        noAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
        signUp: "ਸਾਈਨ ਅੱਪ ਕਰੋ",
        joinAdvisory: "ਫਸਲ ਸਲਾਹ ਨਾਲ ਜੁੜੋ",
        createAccount: "ਆਪਣਾ ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ",
        namePlaceholder: "ਪੂਰਾ ਨਾਮ",
        pincodePlaceholder: "ਪਿੰਨਕੋਡ",
        hasAccount: "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
        signInLink: "ਲਾਗਇਨ ਕਰੋ",
        heroTitle1: "ਸਹੀ ਸਲਾਹ ਨਾਲ ",
        heroTitle2: "ਕਿਸਾਨਾਂ",
        heroTitle3: " ਨੂੰ ਬਣਾਓ ਮਜ਼ਬੂਤ",
        heroDesc: "ਕਿਸਾਨ ਸਹਾਇਕ ਤੁਹਾਨੂੰ ਮੌਸਮ, ਮੰਡੀ ਭਾਅ ਅਤੇ ਵਿਗਿਆਨਕ ਸਲਾਹ ਦੇਣ ਲਈ AI ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ।",
        ctaGetStarted: "ਮੁਫਤ ਸ਼ੁਰੂ ਕਰੋ",
        ctaViewDemo: "ਡੈਮੋ ਦੇਖੋ",
        advTitle: "ਫਸਲ ਸਲਾਹਕਾਰ",
        lblSeason: "ਮੌਸਮ",
        lblSoil: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
        lblWater: "ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ",
        lblLand: "ਜ਼ਮੀਨ (ਏਕੜ)",
        btnGetRec: "ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ",
        bestMatch: "ਸਭ ਤੋਂ ਵਧੀਆ ਫਸਲ",
        goodMatch: "ਚੰਗੀ ਫਸਲ",
        expYield: "ਅਨੁਮਾਨਿਤ ਝਾੜ",
        qPerAcre: "ਕੁਇੰਟਲ/ਏਕੜ",
        estRevenue: "ਅਨੁਮਾਨਿਤ ਆਮਦਨ",
        botGreeting: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਕਿਸਾਨ ਸਹਾਇਕ AI ਹਾਂ। ਆਪਣੀਆਂ ਫਸਲਾਂ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ।",
        botPlaceholder: "ਖਾਦ, ਕੀਟਨਾਸ਼ਕ ਬਾਰੇ ਪੁੱਛੋ...",
        shopTitle: "ਕਿਸਾਨ ਬਜ਼ਾਰ",
        shopDesc: "ਉੱਚ ਗੁਣਵੱਤਾ ਵਾਲੇ ਬੀਜ, ਖਾਦ, ਪੰਪ ਅਤੇ ਸੰਦ।",
        addToCart: "ਕਾਰਟ ਵਿੱਚ ਪਾਓ",
        cartTitle: "ਤੁਹਾਡੀ ਕਾਰਟ",
        checkout: "ਹੁਣੇ ਖਰੀਦੋ"
    },
    gu: {
        brandName: "કિસાન સહાયક",
        navFeatures: "વિશેષતા",
        navAbout: "અમારા વિશે",
        navLogin: "લોગિન",
        navSignUp: "રજિસ્ટર",
        navShop: "દુકાન",
        welcomeUser: "સ્વાગત છે, {name}",
        logout: "લૉગ આઉટ",
        selectLanguage: "ભાષા પસંદ કરો",
        advTitle: "પાક સલાહકાર",
        lblSeason: "ઋતુ",
        lblSoil: "જમીનનો પ્રકાર",
        lblWater: "પાણીની ઉપલબ્ધતા",
        lblLand: "જમીન વિસ્તાર (એકર)",
        btnGetRec: "ભલામણો મેળવો",
        bestMatch: "શ્રેષ્ઠ પાક",
        goodMatch: "યોગ્ય પાક",
        expYield: "અપેક્ષિત ઉપજ",
        botGreeting: "નમસ્તે! હું કિસાન સહાયક AI છું. ખેતી વિશે કંઈપણ પૂછો.",
        botPlaceholder: "ખાતર, જંતુનાશકો વિશે પૂછો...",
        shopTitle: "કિસાન બજાર",
        shopDesc: "ઉચ્ચ ગુણવત્તાવાળા બિયારણ, ખાતર અને સાધનો.",
        addToCart: "કાર્ટમાં ઉમેરો",
        cartTitle: "તમારું કાર્ટ",
        checkout: "હમણાં ખરીદો"
    },
    mr: {
        brandName: "किसान सहायक",
        navFeatures: "वैशिष्ट्ये",
        navAbout: "आमच्याबद्दल",
        navLogin: "लॉगिन",
        navSignUp: "नोंदणी",
        navShop: "दुकान (Shop)",
        welcomeUser: "स्वागत आहे, {name}",
        logout: "लॉग आउट",
        selectLanguage: "भाषा निवडा",
        advTitle: "पीक सल्लागार",
        lblSeason: "हंगाम",
        lblSoil: "मातीचा प्रकार",
        lblWater: "पाण्याची उपलब्धता",
        lblLand: "जमीन क्षेत्र (एकर)",
        btnGetRec: "सल्ला मिळवा",
        bestMatch: "सर्वोत्तम पीक",
        goodMatch: "चांगले पीक",
        expYield: "अपेक्षित उत्पादन",
        botGreeting: "नमस्कार! मी किसान सहायक AI आहे. शेतीबद्दल काहीही विचारा.",
        botPlaceholder: "खते, कीटकनाशके याबद्दल विचारा...",
        shopTitle: "शेतकरी बाजार",
        shopDesc: "उच्च दर्जाचे बियाणे, खते आणि कृषी उपकरणे.",
        addToCart: "कार्टमध्ये जोडा",
        cartTitle: "तुमची कार्ट",
        checkout: "आता खरेदी करा"
    },
    bn: {
        brandName: "কিষাণ সহায়ক",
        navFeatures: "বৈশিষ্ট্য",
        navAbout: "আমাদের সম্পর্কে",
        navLogin: "লগইন",
        navSignUp: "নিবন্ধন",
        navShop: "দোকান",
        welcomeUser: "স্বাগতম, {name}",
        logout: "লগ আউট",
        selectLanguage: "ভাষা নির্বাচন করুন",
        advTitle: "ফসল উপদেষ্টা",
        lblSeason: "মৌসুম",
        lblSoil: "মাটির ধরন",
        lblWater: "পানির সহজলভ্যতা",
        lblLand: "জমির পরিমাণ (একর)",
        btnGetRec: "পরামর্শ পান",
        bestMatch: "সেরা ফসল",
        goodMatch: "ভালো ফসল",
        expYield: "প্রত্যাশিত ফলন",
        botGreeting: "নমস্কার! আমি কিষাণ সহায়ক AI। আপনার চাষাবাদ সম্পর্কে যেকোনো প্রশ্ন করুন।",
        botPlaceholder: "সার, কীটনাশক সম্পর্কে জিজ্ঞাসা করুন...",
        shopTitle: "কৃষক বাজার",
        shopDesc: "উন্নত মানের বীজ, সার এবং কৃষি সরঞ্জাম।",
        addToCart: "কার্টে যোগ করুন",
        cartTitle: "আপনার কার্ট",
        checkout: "এখনই কিনুন"
    },
    ta: {
        brandName: "கிசான் சகாயக்",
        navFeatures: "அம்சங்கள்",
        navAbout: "எங்களை பற்றி",
        navLogin: "உள்நுழை",
        navSignUp: "பதிவு செய்க",
        navShop: "கடை",
        welcomeUser: "வரவேற்கிறோம், {name}",
        logout: "வெளியேறு",
        selectLanguage: "மொழியைக் காண்க",
        advTitle: "பயிர் ஆலோசகர்",
        lblSeason: "பருவம்",
        lblSoil: "மண் வகை",
        lblWater: "நீர் இருப்பு",
        lblLand: "நிலப்பரப்பு (ஏக்கர்)",
        btnGetRec: "பரிந்துரைகளைப் பெறுக",
        bestMatch: "சிறந்த பயிர்",
        goodMatch: "நல்ல பயிர்",
        expYield: "எதிர்பார்க்கப்படும் மகசூல்",
        botGreeting: "வணக்கம்! நான் கிசான் சகாயக் AI. உங்கள் விவசாயம் குறித்து எதையும் கேளுங்கள்.",
        botPlaceholder: "உரம், பூச்சிக்கொல்லி பற்றி கேளுங்கள்...",
        shopTitle: "விவசாயி சந்தை",
        shopDesc: "தரமான விதைகள், உரங்கள் மற்றும் உபகரணங்கள்.",
        addToCart: "கூடையில் சேர்",
        cartTitle: "உங்கள் கூடை",
        checkout: "இப்போதே வாங்கு"
    },
    te: {
        brandName: "కిసాన్ సహాయక్",
        navFeatures: "ఫీచర్లు",
        navAbout: "గురించి",
        navLogin: "లాగిన్",
        navSignUp: "నమోదు",
        navShop: "దుకాణం",
        welcomeUser: "స్వాగతం, {name}",
        logout: "లాగౌట్",
        selectLanguage: "భాషను ఎంచుకోండి",
        advTitle: "పంట సలహాదారు",
        lblSeason: "సీజన్",
        lblSoil: "నేల రకం",
        lblWater: "నీటి లభ్యత",
        lblLand: "భూమి విస్తీర్ణం (ఎకరాలు)",
        btnGetRec: "సిఫార్సులను పొందండి",
        bestMatch: "ఉత్తమ పంట",
        goodMatch: "మంచి పంట",
        expYield: "ఆశించిన దిగుబడి",
        botGreeting: "నమస్తే! నేను కిసాన్ సహాయక్ AI ని. మీ వ్యవసాయం గురించి ఏదైనా అడగండి.",
        botPlaceholder: "ఎరువులు, పురుగుమందుల గురించి అడగండి...",
        shopTitle: "రైతు మార్కెట్",
        shopDesc: "నాణ్యమైన విత్తనాలు, ఎరువులు మరియు పరికరాలు.",
        addToCart: "కార్ట్‌కు జోడించు",
        cartTitle: "మీ కార్ట్",
        checkout: "ఇప్పుడే కొనుగోలు చేయండి"
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguageState] = useState("en");

    const setLanguage = (langCode) => {
        setLanguageState(langCode);
    };

    const t = (key, params = {}) => {
        // Find translation in selected language, fallback to hindi, then english, then key itself
        const langDict = translations[language] || translations.hi || translations.en;
        let str = langDict[key] || translations.en[key] || key;
        
        Object.keys(params).forEach(p => {
            str = str.replace(`{${p}}`, params[p]);
        });
        
        return str;
    };

    const currentLanguageObj = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageObj, LANGUAGES }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}

